-   id: no-view-statement
    name: Detect View() statements
    description: Detects View() statements.
    entry: inst/bin/no-view-statements
    language: script
    types: '(\.R|\.Rmd|\.Rnw|\.r|\.rmd|\.rnw)$'